image: moussavdb/yildiz-build-image

pipelines:
  default:
    - step:
        script:
          - mvn -V -B -s settings.xml package
  branches:
    master:
      - step:
          script:
            - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
            - gpg --import private-key.gpg
            - mvn -V -B -s settings.xml -Pno-native deploy
            - mvn -V -B -s settings.xml -Denv=linux64 clean deploy
            - mvn -V -B -s settings.xml -Denv=win32 clean deploy
            - mvn -V -B -s settings.xml -Denv=win64 clean deploy